blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.profile, name='profile'),
    url(r'^resume$', views.resume, name='resume'),
    url(r'^portfolio$', views.portfolio, name='portfolio'),
    url(r'^portfolio/calculator$', views.calculator, name='calculator'),
    url(r'^portfolio/game$', views.game, name='game'),
    url(r'^portfolio/image_viewer$', views.image_viewer, name='image'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^design$', views.design, name='design'),
    url(r'^board$', views.PostListView.as_view(), name='board'),
    url(r'^save_board$', views.savePostListView.as_view(), name='save_board'),
    url('^post/(?P<pk>[0-9]+)/$', views.postDetailView.as_view(), name='post_detail'),
    url(r'^post/new$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default= timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[str(self.id)])

    class Meta:
        ordering = ['-id']

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views import generic

from blog.forms import PostForm
from blog.models import Post


def profile(request):
    return render(request, 'blog/profile.html')

def resume(request):
    return render(request, 'blog/resume.html')

def portfolio(request):
    return render(request, 'blog/portfolio.html')

def calculator(request):
    return render(request, 'blog/calculator_site.html')

def game(request):
    return render(request, 'blog/game_site.html')

def image_viewer(request):
    return render(request, 'blog/image_viewer_site.html')


def contact(request):
    return render(request, 'blog/contact.html')

def design(request):
    return render(request, 'blog/design.html')

# def board(request):
#     posts = Post.objects.all()
#     return render(request, 'blog/board.html', {'posts': posts} )

class postDetailView(generic.DetailView):
    model = Post





class PostListView(generic.ListView):
    model = Post
    template_name = 'blog/board.html'

    context_object_name = 'posts'
    queryset = Post.objects.filter(published_date__lte=timezone.now())
    paginate_by = 7

class savePostListView(generic.ListView):
    model = Post
    template_name = 'blog/save_board.html'

    context_object_name = 'posts'
    queryset = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    paginate_by = 7


def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)


def post_new(request):
        if request.method == "POST":
            form = PostForm(request.POST)
            if form.is_valid():
                post = form.save(commit=False)
                # post.author = request.user
                post.author = User.objects.get(id=1)
                post.save()
                return redirect('blog:post_detail', pk=post.pk)

            else:
                form = PostForm()
                return render(request, 'blog/post_edit.html', {'form': form})

        else:
            form = PostForm()
            return render(request, 'blog/post_edit.html', {'form': form})


def post_edit(request, pk):
        post = get_object_or_404(Post, pk=pk)
        if request.method == "POST":
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                # post.author = request.user
                post.author = User.objects.get(id=1)
                post.save()
                return redirect('blog:post_detail', pk=post.pk)
        else:
            form = PostForm(instance=post)
        return render(request, 'blog/post_edit.html', {'form': form})


def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:board')

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Yang soon kyu | portfolio</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <style>

    </style>
</head>
<body >
    <header>

        <div class="page-header">
            <h1>
                <a href="{% url 'blog:profile' %}">Yang soon kyu</a>
            </h1>
            <h5>HTML / CSS / JavaScript / Python / SQLite </h5>
        </div>


    </header>
    <div class="main">
        <nav>

            <div>
                <ul>
                    <li><a href="{% url 'blog:profile' %}">Profile</a></li>
                    <li><a href="{% url 'blog:resume' %}">Resume</a></li>
                    <li><a href="{% url 'blog:portfolio' %}">Portfolio</a></li>
                    <li><a href="{% url 'blog:contact' %}">Contact</a></li>
                    <li><a href="{% url 'blog:design' %}">Design</a></li>
                    <li><a href="{% url 'blog:board' %}">Board</a></li>
                </ul>
            </div>
        </nav>
        <section>
            <div  class="mid">
                {% block content %}
                {% endblock %}



            </div>
        </section>
    </div>



    <!-- <div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">

                </div> -->
 <div>

        {% if user.is_authenticated %}
        <p class="logout"><span><a href="{% url 'logout' %}">로그아웃</a></span></p>
{% else%}
        <span class="login"><span>
            <a href="{% url 'login' %}">로그인 </a></span> </span>
    {% endif %}
        </div>
</body>
</html>

blog/templates/blog/board.html
{% extends 'blog/base.html' %} {% block content %}
<style>
    .top {
        /* border: 1px solid white; */
        height: 100px;

    }

    .postList {
        width: 700px;
        height: 500px;
        /* background-color: white; */
        margin-left: 100px;


    }

    hr {
        margin: 3px;
        color: white;
    }

    p {
        margin: 0 0 0 40px;
    }

    .id {
        position: relative;
        top: 9px;
        left: -20px;
    }

    .title {
        position: relative;
        left: 40px;
        font-weight: bold;
    }

    .author {
        position: relative;
        left:60px;
        font-size: 0.9em;
    }

    .postComment {
        position: relative;
        left: 60px;
        font-size: 0.8em;
    }

    .date {
        position: relative;
        left: 480px;
        top: -10px;
    }

    .top p {
        color: white;
        font-weight: bold;
    }

    .page-links{
        background-color: rgb(204, 245, 231);
        position: absolute;
        top: 650px;
        width: 700px;
        display: flex;
    }

    .next{
        position: relative;
        left: 500px;
    }

    .page-current{
        position: absolute;
        left: 280px;

    }

    

    .colorBtn{
        position: absolute;
        top: 220px;
        left: 1150px;
        background-color: #DDF0EC;
        font-weight: bold;
    }

    .saveListBtn{
        left:1075px ;
    }
</style>

<script>
    function moveBoard(){
        location.href ="{% url 'blog:post_new' %}";
    }

    function moveSaveBoard(){
        location.href ="{% url 'blog:save_board' %}";
    }
</script>
<h1 class="sub_h1"> Board</h1>
<div class="top">
    <p>자유 게시판 입니다. 업데이트 진행중입니다. </p>
    <p>로그인을 해주세요 id: admin , pass:양순규 </p>
    <!-- <p class="postNew"><a href="{% url 'blog:post_new' %}"> 글쓰기</a></p> -->
    {% if user.is_authenticated %}
    <input type="button" value ="글쓰기" onclick="moveBoard()" class="colorBtn">
    <input type="button" value ="저장된글" onclick="moveSaveBoard()" class = "colorBtn saveListBtn" >
    {% endif %}
</div>
<div class="postList">

    <hr> {% for post in posts %}
    <p>
        <span class="id">{{ post.id }} </span>
        <span class="title">
            <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
        </span>
    </p>
    <p>
        <span class="author">{{ post.author}} | </span>
        <span class="postComment">comment:</span>
        <span></span>
        <span class="date">{{ post.created_date.year}}. {{ post.created_date.month}}.{{ post.created_date.day}} </span>
    </p>
    <hr> {% endfor %}

    <div class="page-links">
        <p >
            <span class="previous">
                {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">이전 페이지</a>
                {% endif %}</span>
            <span>
                <span >
                    <p class="page-current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</p>
                </span>
            </span>
            <span class="next">
                {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">다음 페이지</a>
                {% endif %}
            </span>




        </p>

    </div>
</div>



{% endblock%}

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block content %}
<style>
    canvas{
        position: relative;
        top: 80px;
        left: 110px;
        background-color: white;
        box-shadow: 2px 2px 5px black;
    }

    .email{
        position: absolute;
        top: 576px;
        left: 598px;
        }

    .mobile{
        position: absolute;
        top: 576px;
        left: 798px;
    }

    .address{
        position: absolute;
        top: 578px;
        left: 973px;
        font-size: 0.9em;
    }
</style>
<h1 class="sub_h1"> My Contact</h1>
<div>

    <canvas id= "myCanvas" width="660" height="420"></canvas>
    <p class="email">t_j4331@naver.com</p>
    <p class="mobile">010 2405 4305</p>
    <p class="address">전주시 완산구 고사평5길 (서신동)</p>
</div>

<script>
    var myCanvas = document.getElementById("myCanvas");
    var ctx = myCanvas.getContext("2d");
    ctx.font = "20px Arial";
    ctx.fillText("양 순 규", 250,140);
    ctx.font = "13px Arial";
    ctx.fillText("신입 개발자", 330, 140)
    ctx.fillText("Yang Soon Kyu", 250,160)
    ctx.fillText("Developer", 346,160)
    ctx.fillText("E-mail  | ", 20,360)
    ctx.fillText("Mobile  | ", 220,360)
    ctx.fillText("Address |  ",390,360)
    ctx.font = "30px Arial";
    ctx.fillStyle = "darkblue"
    ctx.fillText("함께 일하고 싶습니다.", 90,230)
    ctx.font = "18px Arial";
    ctx.fillStyle = "darkblue";
    ctx.fillRect(80,240, 620, 10);



</script>

{% endblock %}

blog/templates/blog/design.html
{% extends 'blog/base.html' %} {% block content %}
<style>
    .d_img{
        position: relative;
        left: 20px;
        width: 850px;
        height:600px;
        overflow: scroll;
        overflow-x: hidden;
    }

    img{
        margin: 20px;
        box-shadow: 2px 2px 5px black;
    }
</style>
<h1 class="sub_h1">My Design</h1>
<div class="d_img">
    <div class="column">
        <img src="/static/images/D_fort/엘리베이터 거울.jpg" style="width:28%">
        <img src="/static/images/D_fort/게시판 업로드 이미지.jpg" style="width:28%">
        <img src="/static/images/D_fort/포토스토리 수정 전 후.jpg" style="width:28%">
        <img src="/static/images/D_fort/간판1.jpg" style="width:28%">
        <img src="/static/images/D_fort/간판2.jpg" style="width:28%">
        <img src="/static/images/D_fort/간판3.jpg" style="width:28%">
    </div>

    <div class="column">
        <img src="/static/images/D_fort/건어물 시장 간판 최종.jpg" style="width:28%">
        <img src="/static/images/D_fort/시장집 서신본점 간판.jpg" style="width:28%">
        <img src="/static/images/D_fort/바디앤소울로고.jpg" style="width:28%">
    </div>
    <div class="column">
        <img src="/static/images/D_fort/로고1.jpg" style="width:28%">
        <img src="/static/images/D_fort/로고2.jpg" style="width:28%">
        <img src="/static/images/D_fort/유니폼3.jpg" style="width:28%">
    </div>

    <div class="column">
            <img src="/static/images/D_fort/이미지 10.jpg" style="width:28%">
            <img src="/static/images/D_fort/유니폼1.jpg" style="width:28%">
            <img src="/static/images/D_fort/유니폼2.jpg" style="width:28%">
        </div>

        <div class="column">
                <img src="/static/images/D_fort/명함.jpg" style="width:28%">
                <img src="/static/images/D_fort/다가점 전단지.jpg" style="width:28%">
                <img src="/static/images/D_fort/이미지 18.jpg" style="width:28%">
                <img src="/static/images/D_fort/노리야 메뉴판.jpg" style="width:28%">
            </div>
</div>
{% endblock %}

blog/templates/blog/portfolio.html
{% extends 'blog/base.html' %} {% block content %}
<style>
    img {
        float: left;
        margin-right: 20px;
        border: 1px solid wheat;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2)
    }

    
    .port_main {
        display: flex;
        flex-direction: column;
        margin: 20px;
    }

    .port_main>div {
        /* border: rgb(165, 247, 229) solid 1px; */
        padding: 3px;
        margin: 10px;
        font-weight: bold;
        font-size: 1em;
    }

    .Link span {
        display: flex;
        display: inline-block;
        position: relative;
        left: 490px;
        top: -40px;
        padding: 2px;
        color: #262623;
        background-color: #DDF0EC;
        margin: 2px;
    }

    .port_main p {
        margin-top: 2px;
        color: #0d7373;
        font-size: 1.3em;
    }

    .text {
        overflow: scroll;
        overflow-x: hidden;
        width: 600px;
        height: 100px;
        position: absolute;
        top: 230px;
        left: 680px;
        color: black
    }

    .text p {
        margin: 1px;
    }

    .txt2 {
        position: absolute;
        top: 383px;
    }

    .txt3 {
        position: absolute;
        top: 539px;
    }

    .used{
        position: relative;
        color: #035e5e;
        font-size: 0.9em;
        font-weight: 100;
        left: 5px;
        top: -15px;
    }
</style>
<h1 class="sub_h1"> My Portfolio</h1>
<div class="port_main">

    <div class="port1">
        <a href="{% url 'blog:calculator' %}" target="_blank">
            <img src="/static/images/port1.jpg" alt="" width="200">
        </a>
        <p>사칙연산 + 생활계산기 </p>
        <span class="used"> HTML / CSS / JavaScript</span>
        <div class="Link">
            <span>
                <a href="{% url 'blog:calculator' %}" target="_blank">화면보기</a>
            </span>
            <span>
                <a href="https://github.com/yangsoonkyu/portfolio1/blob/master/blog/templates/blog/calculator_site.html" target="_blank">소스보기</a>
            </span>
        </div>
        <br>
    </div>
    <div class="port2">
        <a href="{% url 'blog:game' %}" target="_blank">
            <img src="/static/images/port2.jpg" alt="" width="200">
        </a>

        <p>물고기 피하기 게임</p>
        <span class="used"> HTML / CSS / JavaScript</span>
        <div class="Link">
            <span>
                <a href="{% url 'blog:game' %}" target="_blank">화면보기</a>
            </span>
            <span>
                <a href="https://github.com/yangsoonkyu/portfolio1/blob/master/blog/templates/blog/game_site.html" target="_blank">소스보기</a>
            </span>

        </div>

    </div>
    <div class="port3">
        <a href="{% url 'blog:image' %}" target="_blank">
            <img src="/static/images/port3.jpg" alt="" width="200">
        </a>

        <p>이미지 뷰어</p>
        <span class="used"> HTML / CSS / JavaScript</span>
        <div class="Link">
            <span>
                <a href="{% url 'blog:image' %}" target="_blank">화면보기</a>
            </span>
            <span>
                <a href="https://github.com/yangsoonkyu/portfolio1/blob/master/blog/templates/blog/image_viewer_site.html" target="_blank">소스보기</a>
            </span>

        </div>
    </div>

</div>
<div class="text">
    <p>수식을 입력하여 사칙연산 수행할수 있습니다</p>
    <p>입력수식과 결과를 화면에 보여줍니다</p>
    <p>키보드 단축키 기능이 있습니다</p>
    <p>BMI, 평방미터 계산 기능이 있습니다</p>
</div>
<div class="text txt2">
    <p>키보드 방향키로 조작하여 플레이합니다</p>
    <p>물고기(장애물)을 피하는 게임입니다</p>
    <p>스코어에 따라 스테이지가 나누어집니다</p>
    <p>게임오버되면 게임을 다시 시작할수 있습니다</p>
</div>
<div class="text txt3">
    <p>이미지 파일을 불러와서 화면에 나타낼수 있습니다.</p>
    <p>이미지 위에 마우스를 올리면 실제사이즈 보기(뷰어)가 가능합니다</p>
    <p>마우스를 내리면 뷰어가 종료됩니다.</p>
    <p>뷰어에 보이는 화면은 마우스의 좌표에 따라 바뀝니다.</p>
    <p>이미지 안의 마우스위치를 나타네는 사각형은 이미지 밖으로 나갈수 없습니다</p>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} {% block content %}
<style>
    .top {
        /* border: 1px solid white; */
        height: 100px;

    }

    .postDetail {
        width: 700px;
        height: 500px;
        /* background-color: white; */
        margin-left: 100px;
    }

    .authorLeft {
        position: absolute;
        left: 1100px;
    }

    .title {
        font-weight: bold;
        font-size: 1.3em;
    }

    .top p {
        color: white;
        font-weight: bold;
    }

    .colorBtn {
        position: absolute;
        top: 220px;
        left: 1150px;
        background-color: #DDF0EC;
        font-weight: bold;
    }

    .colorBtn2 {
        background-color: #DDF0EC;
        font-weight: bold;
    }

    .published {
        position: relative;
        left: 590px;
        top: -30px;
        font-size: 0.8em;
    }

    .pubBtn2 {
        background-color: #DDF0EC;
        font-weight: bold;
        position: relative;
        left: 620px;
        top: -30px;

    }
</style>
<script>
    function moveBoard() {
        location.href = "{% url 'blog:board' %}";
    }

    function movePublish() {
        location.href = "{% url 'blog:post_publish' pk=post.pk %}";
    }
    
    function moveEdit() {
        location.href = "{% url 'blog:post_edit' pk=post.pk %}";
    }

    function moveRemove() {
        location.href = "{% url 'blog:post_remove' pk=post.pk %}";
    }
    

</script>
<h1 class="sub_h1">Board</h1>
<div class="top">
    <p>자유 게시판 입니다. 업데이트 진행중입니다.</p>
    <input type="button" value="목록으로" onclick="moveBoard()" class="colorBtn">
</div>

<div class="postDetail">
    <p>
        <span class="title">{{post.title}}</span>
    </p>
    <hr> {{post.text}}
    <br>
    <br>
    <p class="authorLeft">
        <span>{{post.author}}</span>
        <span> {{post.created_date.year}}.{{post.created_date.month}}.{{post.created_date.day}}</span>
    </p>
    <br>
    <hr>
    <div>
        {% if user.is_authenticated %}
       
            <span>
                <input type="button" value="수정" onclick="moveEdit()" class="colorBtn2">
            </span>
        
        <span>
            <input type="button" value="삭제" onclick="moveRemove()" class="colorBtn2">
        </span>
        {% endif %} {% if post.published_date %}
        <div class="published">
            published : {{ post.published_date.year }}.{{ post.published_date.month }}.{{ post.published_date.day }}
        </div>
        {% else %}
        <div>
            <input class="pubBtn2" type="button" value="Publish" onclick="movePublish()">
        </div>

        {% endif %}
    </div>


</div>



{% endblock%}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %} {% block content %}
<style>
    .top {
        /* border: 1px solid white; */
        height: 100px;

    }

    .postedit {
        width: 700px;
        height: 500px;
        /* background-color: white; */
        margin-left: 100px;


    }

    .top p {
        color: white;
        font-weight: bold;
    }

    #id_title {
        width: 600px;
    }

    #id_text {
        width: 600px;
        height: 320px;
    }

    /* #idSubmit{
        position: relative;
        left: 550px;
    } */

    .colorBtn{
        background-color: #DDF0EC;
        font-weight: bold;
    }

    label{
        display: flex;
        margin-top: 3px;
    }
</style>
<div class="top">
    <p>자유 게시판 입니다. 업데이트 진행중입니다.</p>
    <!-- <span>
        <a href="{% url 'blog:post_new' %}"> 글쓰기</a>
    </span> -->
</div>
<div class="postedit">
    <form action="" method="POST" onkeydown="enterCheck();">{% csrf_token %}

            {{form}}
       
        
        <span id="idSubmit">
            <input type="submit" value="저장" class="colorBtn" >
            <input type="button" value ="취소" onclick="moveBoard()" class="colorBtn">
        </span>

        
    </form>

</div>

<script>

    function moveBoard(){
        location.href ="{% url 'blog:board' %}";

    }


</script>
{% endblock %}

blog/templates/blog/profile.html
{% extends 'blog/base.html' %} {% block content %}
<h1 class="sub_h1"> About Me</h1>
<style>
    .profile {
        margin-right: 20px;
        margin-left: 20px;
    }

    img {
        border: 1px solid lightgray;
        position: relative;
        top: 10px;
        margin-right: 3px;
    }

    .name {
        position: absolute;
        top: 380px;
        left: 800px;
        font-weight: bold;
        font-size: 1.5em;
    }

    .contact {
        position: absolute;
        top: 425px;
        left: 790px;
        color: gray;

        font-size: 0.85em;
    }

    .len {
        border: 1px solid lightgray;
        border-radius: 5px;
        padding: 1px 5px 1px 5px;
    }

    .phone {
        position: absolute;
        left: 1090px;
    }

    .ins {
        position: absolute;
        left: 1190px;
    }

    .none {
        position: absolute;
        left: 1036px;
    }

    .profile_txt{
        position: absolute;
        top: 440px;
        left: 798px;
    }

    .profile_txt p{
        margin: 0px;
        font-size: 0.93em;
    }

    .comment{
        position: absolute;
        top: 720px;
        left: 490px;;
        font-size: 0.8em;
        color: orangered;
    }
    section{ background-color: white;}

</style>



<div class="profile">
    <img src="/static/images/Kakao.png" alt="" style="width:330px;">
    <img src="/static/images/Kakao2.jpg" alt="" style="width:500px;">
    <!-- <img src="/static/images/프로필.jpg" alt="" style="width:200px;"> -->
    <div class="profile">
        <p class="name">양순규</p>
        <p class="contact len">HTML/ CSS / JavaScript / Python</p>
        <p class="contact phone">010 2405 4305</p>
        <a href="https://www.instagram.com/y__xkyu/" target="_blank"><p class="contact ins">y__xkyu</p></a>
        <p class="contact none">1:1</p>


    </div>
    <div class="profile_txt">
        <h3>프로그래밍 공부하면서 가장 많이 들은 말!</h3>

        <p>제가 프로그래밍을 시작하게 된 계기는 전자제품에 대한 관심으로 시작되었습니다</p>
        <p>새로운 기술들이 쏟아져 나오고 있고 경험하며 살아가면서 사용만 하는게 아니라</p>
        <p>나도 한번 새로운 것들을 만들 수 있지 않을까 생각하게 되었습니다.</p>
        
        <p>조금 늦게 시작한 감이 있지만 그래도 응원과 함께 가장 많이 들었던 말은</p>
        <p>'잘 어울린다' 입니다</p>
        <p>그만큼 컴퓨터와 가갑게 지냈고 동아리 활동도 했으며 컴퓨터 잘 아는 친구로</p>
        <p> 통했기 때문에 배움에 있어 흥미를 느끼게 되었습니다 </p>

        <p>공부를 시작하면서 전혀 다른 분야와 처음듣는 용어들로 당황스러웠지만</p>
        <p>코드를 입력해서 프로그램을 만든다는게 신기했고 응용해서  </p>
        <p>기능을 추가하는 일들이 재미있게 느껴졌습니다</p>

        <p>아직은 신입으로써 배워야할 점이 더 많지만 즐거운 마음으로 일하고싶습니다 </p>
        
    </div>
    <div>
    <span class="comment"> * 실제 대화 내용을 각색하였습니다.</span>   
    </div>

</div>



{% endblock %}